# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML7', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
